version: '3.3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "81:80"
      - "443:443"

    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./www:/var/www
      - ./logs:/var/log/nginx
    links:
      - db
      - php

    php:
      build: ./images/php
      volumes:
        - ./www:/var/www
      links:
        - db
        - memcached
      ports:
        - "9000:9000"

    db:
      image: mariadb:latest
      restart: always
      volumes:
        - ./mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=123
      ports:
        - "3306:3306"

    memcached:
        image: memcached:latest

    adminer:
        image: adminer
        restart: always
        ports:
          - "8080:8080"
        links:
          - db

    composer:
        image: composer:latest
        volumes:
          - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
        command: composer install
        working_dir: ${APP_PATH_CONTAINER}

volumes:
  mysql: {}
